###################################
#        Basic Services           #
#           for x86               #
#                                 #
#    Do not use for Production!   #
#         J-Ha – @_j_ha           #
#                                 #
###################################
version: '2'
services:
  push_python:
    image: thexero/gpnpush:latest
    container_name: push_python
    networks:
      - badge_push
    volumes:
      - ./settings.py.sample:/usr/src/app/settings.py

  push_database:
    image: postgres
    container_name: push_database
    networks:
      - badge_push
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  haproxy:
    image: haproxy
    container_name: haproxy
    volumes:
      - ./server.pem:/etc/ssl/server.pem
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg 
    networks:
      - badge_push
    ports:
      - "80:80"
      - "443:443"

networks:
  badge_push:
    driver: bridge